import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';

import Navigation from '@/components/shared/Navigation';
import Footer from '@/components/shared/Footer';

import './globals.css';

const font = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Rezidence Marica',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body
        className={`${font.className} flex flex-col justify-start h-screen`}
      >
        <Navigation />
        <main className="w-full">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
